name: Publish Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build and doc dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "meson-python>=0.17.1" "meson>=1.3" "ninja" "Cython>=3.0.10" "numpy>=1.22.0" "scipy>=1.14.0" "scikit-learn>=1.5.0"
          python -m pip install -e . --no-build-isolation
          python -m pip install .[docs]

      - name: Sphinx build
        working-directory: doc
        env:
          PFLM_VERSION: ${{ github.ref_name }}
        run: |
          python -m sphinx -b html source build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
          force_orphan: true
