name: Publish Sphinx Documentation

on:
  push:
    branches:
      - main

jobs:
  publish_sphinx_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install numpy scipy scikit-learn cython meson-python
          python -m pip install -e . --no-build-isolation
          python -m pip install .[docs]
      - name: Sphinx build
        run: |
          cd doc
          python -m sphinx -b html source build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
