name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[tests]
        python -m pip uninstall -y pflm
        python -m pip install --verbose --no-build-isolation --editable . --config-settings editable-verbose=true --config-settings build-dir=build/gha-${{ runner.os }}-${{ matrix.python-version }}

    - name: ruff check
      run: |
        ruff check pflm

    - name: Test with pytest
      run: |
        python -m pytest . -v
